workflows:
  android-build:
    name: Android Build
    environment:
      node: 18
      vars:
        PACKAGE_NAME: "com.amazonflexclone.app"
        EXPO_PROJECT_ID: "AmazonFlexClone"
        CI: 1
        EXPO_TOKEN: "RRFWQu6Vk7QKsvenRaxrbUujXV0c-lCf7JpyU-0S"
    scripts:
      - name: Install Expo & EAS CLI
        script: |
          npm install -g expo-cli eas-cli

      - name: Install dependencies
        script: |
          npm install

      - name: EAS Login
        script: |
          eas whoami || eas login --token=$EXPO_TOKEN

      - name: Build APK using EAS
        script: |
          eas build --platform android --profile preview --non-interactive

          # Find the APK path in the output folder
          APK_PATH=$(find . -name "*.apk" | head -n 1 || true)

          if [ -f "$APK_PATH" ]; then
            echo "✅ APK generated at: $APK_PATH"
            mkdir -p $FCI_EXPORT_DIR/apk
            cp "$APK_PATH" $FCI_EXPORT_DIR/apk/
          else
            echo "❌ APK not found. Skipping export step."
          fi

    artifacts:
      - $FCI_EXPORT_DIR/apk/*.apk

    publishing:
      email:
        recipients:
          - Femi4all@gmail.com
      scripts:
        - name: Build completed
          script: |
            echo "✅ EAS APK built successfully (if no errors above)."
            echo "You can download it from the artifacts section."
