workflows:
  android-build:
    name: Android Build
    environment:
      node: 18
      vars:
        PACKAGE_NAME: "com.amazonflexclone.app"
    scripts:
      - name: Clean install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install --force --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Set up Android SDK
        script: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --clean
      - name: Fix Gradle permissions
        script: |
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com 
