workflows:
  android-build:
    name: Android Build
    environment:
      node: 18
      vars:
        PACKAGE_NAME: "com.amazonflexclone.app"
        EXPO_PROJECT_ID: "AmazonFlexClone"
        CI: 1
        EXPO_TOKEN: "RRFWQu6Vk7QKsvenRaxrbUujXV0c-lCf7JpyU-0S"
    scripts:
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Install dependencies
        script: |
          npm install
      - name: Debug environment
        script: |
          echo "Current directory: $PWD"
          ls -la
          echo "FCI_BUILD_DIR: $FCI_BUILD_DIR"
          ls -la $FCI_BUILD_DIR
          
      - name: Setup build environment
        script: |
          # Setup Android SDK path
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "android/local.properties"
          
          # Install dependencies
          npm install
          
          # Setup Gradle
          cd android
          chmod +x gradlew
          
          # Clean Gradle
          ./gradlew clean
          
          # Show environment info
          ./gradlew -v
          
      - name: Build Android APK
        script: |
          cd android
          
          # Build with detailed error output
          ./gradlew assembleRelease --stacktrace --info
    artifacts:
      - build/**/outputs/**/*.apk
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
      scripts:
        - name: Build completed
          script: |
            echo "APK built successfully!"
            echo "You can download the APK from the artifacts section." 
