workflows:
  android-build:
    name: Android Build
    environment:
      node: 18
      vars:
        PACKAGE_NAME: "com.amazonflexclone.app"
    scripts:
      - name: Clean install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install --force --legacy-peer-deps
      - name: Install EAS CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Build APK with EAS
        script: |
          eas build --platform android --non-interactive --local
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com 
