workflows:
  android-build:
    name: Android Build
    environment:
      node: 18
      vars:
        PACKAGE_NAME: "com.amazonflexclone.app"
        EXPO_PROJECT_ID: "AmazonFlexClone"
        CI: 1
        EXPO_TOKEN: "RRFWQu6Vk7QKsvenRaxrbUujXV0c-lCf7JpyU-0S"
    scripts:
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Install dependencies
        script: |
          npm install
      - name: Setup Android SDK
        script: |
          unset EXPO_TOKEN
          eas login -u emman8 -p RRFWQu6Vk7QKsvenRaxrbUujXV0c-lCf7JpyU-0S --non-interactive
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          # Ensure gradlew has execute permissions
          chmod +x ./gradlew
          # Run Gradle with debug output
          ./gradlew assembleRelease --debug
    artifacts:
      - build/**/outputs/**/*.apk
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
      scripts:
        - name: Build completed
          script: |
            echo "APK built successfully!"
            echo "You can download the APK from the artifacts section." 
