workflows:
  android-build:
    name: Android Build
    environment:
      node: 18
      vars:
        PACKAGE_NAME: "com.amazonflexclone.app"
    scripts:
      - name: Clean install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install --force --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Check project structure
        script: |
          ls -la
          pwd
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --clean --non-interactive
      - name: Check Android folder
        script: |
          ls -la android/
          ls -la android/app/
      - name: Fix Gradle permissions
        script: |
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace --info
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com 
